### ISSUE TITLE
some files have 'drug' not set, some have 'none' (including level 1-4)

### ISSUE THREAD

**Issue by kdaily** [MEP-LINCS/MEP_LINCS#117]

**Comment by kdaily** [comment]
These include many files of `"DataType" = "ClarionID"` that have `"drug" = "none"`.

**Comment by kdaily** [comment]
Release notes describe AU565 and HCC1954 to be with lapatanib and no drug, but some files also have `"Drug" = "DMSO"` (all are `"StainingSet" = "SS100"` - what is that?)

**Comment by kdaily** [comment]
Many other cell lines have `"Drug" = "none"` and `"Drug" = (Not set)`. if there was no drug vs no drug, those should all be Not set.

**Comment by markdane** [comment]
I edited the release notes to reflect that the "no drug" plates in the AU565 and HCC1954 contain the drug vehicle DMSO.

All files associated with all other datasets should have "Drug" = (Not set).

**Comment by kdaily** [comment]
OK - will adjust all other cell lines to unset `Drug` - thanks!

**Comment by kdaily** [comment]
done
