### ISSUE TITLE
Remove the scratch folder

### ISSUE THREAD

**Issue by kdaily** [MEP-LINCS/MEP_LINCS#34]
This is only for the pre-release section, not for final release.

**Comment by kdaily** [comment]
@markdane - should decide if any files in there are necessary, else we can delete them.

**Comment by kdaily** [comment]
Forgot to ask you @markdane about any of the files in here!

**Comment by markdane** [comment]
Those can all be deleted

**Comment by kdaily** [comment]
Deleted.
