### ISSUE TITLE
Missing metadata fields - Well, Barcode, Location

### ISSUE THREAD

**Issue by kdaily** [MEP-LINCS/MEP_LINCS#36]
The Well, Barcode, and Location annotations were previously used, but are missing now. Are these deprecated?

**Comment by kdaily** [comment]
See https://www.synapse.org/#!Synapse:syn7494072/tables/ for the current files in this release.

**Comment by markdane** [comment]
These are annotations we used on the raw data files. We aren't including the raw feature values in this release. Files with level 1 and higher data come from multiple barcodes, wells and locations. I don't think we should be annotating these with that information.

**Comment by kdaily** [comment]
There aren't any experimental artifacts that might come from these that
someone getting level 0 (or 1) might want to know about? I think Elmar was
correct that we should push as much annotations from Annot! as possible.
This doesn't need to be displayed in every case (as you're right it might
be distracting or confusing), but once we get his system hooked in we
should pull more in.

I'll leave it out for now though.

On Nov 3, 2016 15:35, "Mark Dane" notifications@github.com wrote:

These are annotations we used on the raw data files. We aren't including
the raw feature values in this release. Files with level 1 and higher data
come from multiple barcodes, wells and locations. I don't think we should
be annotating these with that information.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/MEP-LINCS/MEP_LINCS/issues/36#issuecomment-258294668,
or mute the thread

**Comment by markdane** [comment]
The level 0 data is contained in the level 1 data along with curated An! annotations and LINCS IDs. I agree that the full complement of An! annotations should be on synapse. When they are, the primary keys to link to them are already included in this data.

The biggest source of artifacts in the data comes from the pipeline between the images and the raw (level 0) data. When we make it feasible for users to create their own version of this pipeline, we should also give them the level 0 data.

**Comment by kdaily** [comment]
Thanks Mark, sounds like a plan.
