### ISSUE TITLE
Notes from October 2016 meeting

### ISSUE THREAD

**Issue by kdaily** [MEP-LINCS/MEP_LINCS#37]
Notes I made for improvements to project page(s), among other things. Will turn into issues as necessary.

## New features
1. Discussion forum
    a. Require a code of conduct?
    a. Info for welcome message
    a. Seed with some common FAQ-type questions/answers
1. Provenance checking (validate expected relationships of all files)
1. Data 'views' - provide alternative to file hierarchy view of data (schema to control annotations) - will provide current state, able to snapshot to a frozen data release ([Example](https://www.synapse.org/#!Synapse:syn7346542/tables/); 3-4 weeks)
1. Faceted search - 3-4 weeks ([Mock-up](https://sagebionetworks.jira.com/wiki/display/PLFM/Table+Faceted+Navigation))

## Needs
1. Need more info on assay background, specifically image processing (I have some images from slides)
1. Description of what the 'signature' is from MEP-LINCS (relate terms to LINCS definitions of `cellular signatures` and `cellular phenotype`)
1. Availability of raw data, images (even if not completely available now, some description)
1. Better (layperson) description of the WHY of MEP-LINCS
1. Descriptions of columns in data files (have some in [Curated Features](https://www.synapse.org/#!Synapse:syn7187256))
1. Improvements to provenance
1. Concept of 'controls'

## Discuss
1. Notifications to users - files have changed, new releases, other info
1. Update key personnel profiles (images, info)
1. Connecting annotations to Annot!

**Comment by markdane** [comment]
Let's discuss the New Features and determine which should be acted on now.

Needs 5) Do you have an idea of how we can display the information in the Curated Features file that is useful to end users?

Needs 6) What improvements should we make to the provenances?

Needs 7) Is this an explanation in one of the wikis?
