### ISSUE TITLE
Upload raw data and connect to provenance

### ISSUE THREAD

**Issue by kdaily** [MEP-LINCS/MEP_LINCS#39]

**Comment by kdaily** [comment]
Should always upload the raw data in unaltered form. It can go here:

https://www.synapse.org/#!Synapse:syn7525205

**Comment by kdaily** [comment]
Looks like upload is done, @markdane?

**Comment by markdane** [comment]
It’s happening now and involves 1600+ files. Not sure how far along it is….

**Comment by kdaily** [comment]
looks like about 1/3 done (500 files uploaded). thanks!

**Comment by markdane** [comment]
Done with annotations appropriate to query by CellLine and Staining Set. Level 1 files now link to their raw data files. There are 256 raw files that combine into one Level 1 file so the preview of a Level 1 file throws a spinning ball icon while it loads ~1 minute from a home connection.
