### ISSUE TITLE
Define protocol for data upload, processing and release

### ISSUE THREAD

**Issue by kdaily** [MEP-LINCS/MEP_LINCS#40]
1. Upload raw data with annotations (future: provenance linking back to image processing) to pre-release folder
1. Run processing scripts, upload processed files with provenance to raw data, all annotations (to pre-release folder)
1. Refine processing, QA, reports, etc (going back to 2 if necessary) (to pre-release folder)
1. Write release notes (linking back to existing docs where possible) 
1. Run data release script, move data from pre-release folder to release area
1. Move existing release notes to archive folder
1. Add new release notes to release Wiki page

**Comment by kdaily** [comment]
On last convo w/ @markdane, he is going to provide me with the initial steps that he runs now and I will work on streamlining:
1. Put raw (level 0) data on Synapse with annotations
2. Consume and aggregate level 0 files across `StainingSet` and `CellLine` from Synapse, using the supplied annotations to find files.

Check that going between those two steps on the same machine doesn't have a huge performance penalty, redownloads data, etc.

**Comment by markdane** [comment]
Step 1. is done

For step 2 I need to provide a write up on running the script MEP-LINCS_PreprocessingL1L2.R

**Comment by markdane** [comment]
Closing as the few remaining actions have specific open issues against them.
