### ISSUE TITLE
define new levels

### ISSUE THREAD

**Issue by kdaily** [MEP-LINCS/MEP_LINCS#43]
1. QA_SpotMEP
1. Analysis
1. AnalysisSB
1. QA_Cell

**Comment by kdaily** [comment]
In release notes and in [table](https://www.synapse.org/#!Synapse:syn5662377/tables/query/eyJsaW1pdCI6MjUsICJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjU2NjIzNzcgV0hFUkUgQ2F0ZWdvcnk9J0xldmVsJyIsICJpc0NvbnNpc3RlbnQiOnRydWUsICJvZmZzZXQiOjB9)

**Comment by markdane** [comment]
done. Pls check that this is correct.

**Comment by kdaily** [comment]
Looks good! Will update wiki with info.
