### ISSUE TITLE
Use character for levels

### ISSUE THREAD

**Issue by kdaily** [MEP-LINCS/MEP_LINCS#45]
Because of how the views are defined, all values of an annotation need to have the same type. Since our `Level` annotation has character values (for QC reports, etc), the numeric levels need to be stored as characters as well.

**Comment by markdane** [comment]
fixed

**Comment by kdaily** [comment]
Will have to go back to existing annotations to fix, though (and `forceVersion=FALSE` when modifying). Will open separate issue.
