### ISSUE TITLE
missing 'Location' annotation

### ISSUE THREAD

**Issue by kdaily** [MEP-LINCS/MEP_LINCS#50]
New raw files missing Location annotation.

**Comment by markdane** [comment]
Location is an annotation for raw files. The CP pipeline divides the data based on where in the cell it makes the measurement. These values include nuclei, cell and cytoplasm. There is also an image value that we are not currently using but are likely to use in the future for image level QA.
Level 1 and later files combine data from all locations. I don't see value in having this type of annotation for those files but let me know if you do.

**Comment by kdaily** [comment]
Yes, we must have these as annotations! 

To move the raw processing code to handle files from Synapse, they need to be annotated. The current method of relying on file naming and directory structure conventions is not scalable or reproducible.
