### ISSUE TITLE
new annotation(s) not defined

### ISSUE THREAD

**Issue by kdaily** [MEP-LINCS/MEP_LINCS#51]
What is 'Compartment'?

**Comment by markdane** [comment]
Compartment should have been replaced by Location. Please let me know where you see it. If it's in the phase 1 data, I don't see an immediate need to update it.

**Comment by kdaily** [comment]
It means things can't be identified by the same annotation, so querying is
broken between these datasets.

**Comment by markdane** [comment]
@kdaily It's okay for now to have a disconnect between these datasets. We will discuss reanalyzing and annotating these datasets using the current pipelines. This would also take care of the disconnects.
