### ISSUE TITLE
think about repo name change

### ISSUE THREAD

**Issue by kdaily** [MEP-LINCS/MEP_LINCS#75]
Something more descriptive - something with 'pipeline' in it?

**Comment by markdane** [comment]
@kdaily This repo has the preprocessing pipeline scripts and the QA and analysis reports. We already have a folder named pipeline and I'd like to avoid changing that. I'm thinking "PrePro_Analyze" or simply "scripts"

**Comment by markdane** [comment]
@kdaily I went with Processing as the new name. It includes Pipeline, Reports and archive folders.

**Comment by kdaily** [comment]
Hate to suggest after the fact, but how about MEP_Processing?

**Comment by markdane** [comment]
done
