### ISSUE TITLE
image ids missing Level metadata

### ISSUE THREAD

**Issue by kdaily** [MEP-LINCS/MEP_LINCS#88]
https://www.synapse.org/#!Synapse:syn7494072/tables/query/eyJsaW1pdCI6MjUsICJzZWxlY3RlZEZhY2V0cyI6W3siY29uY3JldGVUeXBlIjoib3JnLnNhZ2ViaW9uZXR3b3Jrcy5yZXBvLm1vZGVsLnRhYmxlLkZhY2V0Q29sdW1uVmFsdWVzUmVxdWVzdCIsICJjb2x1bW5OYW1lIjoiTGV2ZWwiLCAiZmFjZXRWYWx1ZXMiOlsib3JnLnNhZ2ViaW9uZXR3b3Jrcy5VTkRFRklORURfTlVMTF9OT1RTRVQiXX1dLCAic3FsIjoiU0VMRUNUICogRlJPTSBzeW43NDk0MDcyIiwgImlzQ29uc2lzdGVudCI6dHJ1ZSwgIm9mZnNldCI6MH0=

**Comment by markdane** [comment]
I would assign them a value of Metadata but this depends on how we decide handling having this value in both Level and DataType annotations.

**Comment by markdane** [comment]
Made an ImageID DataType, not a Level annotation
