### ISSUE TITLE
set annotations on files in Misc folder

### ISSUE THREAD

**Issue by kdaily** [MEP-LINCS/MEP_LINCS#89]
https://www.synapse.org/#!Synapse:syn8698827

**Comment by markdane** [comment]
@kdaily These are "one of a kind" files that I don't think will be found by query. Few of our existing annotations would make sense on them. What are your thoughts here?

**Comment by kdaily** [comment]
Should annotate w/ staining set and cell line? maybe ok if we move them out of the normal structure; but they need documentation then if they are part of the release (also OK if they are not part of the release).
