### ISSUE TITLE
documentation on new files

### ISSUE THREAD

**Issue by kdaily** [MEP-LINCS/MEP_LINCS#92]
Many new file types - image id, an2omero, etc. Need documentation on what/where/why.

**Comment by markdane** [comment]
@kdaily What are your thoughts on where to add this documentation? In the Annotation Standard table? I think it gets lost there but I don't see a better location.

**Comment by kdaily** [comment]
Would say on release notes and in annotation standard (or what I re-create with the JSON file that's currently here: https://github.com/Sage-Bionetworks/synapseAnnotations/blob/lincs/synapseAnnotations/data/lincs_annotations.json).

**Comment by kdaily** [comment]
Still need these...
