### ISSUE TITLE
describe what will be released based on cell line, staining set, etc.

### ISSUE THREAD

**Issue by kdaily** [MEP-LINCS/MEP_LINCS#96]

**Comment by markdane** [comment]
This release includes:
3 cell lines: MCF10A, HMEC122L, HMEC240L
10 studies: MCF10A_SS1, MCF10A_SS2, MCF10A_SS3, HMEC122L_SS1, HMEC122L_SS4, HMEC240L_SS1, HMEC240L_SS4, MCF10A_SSC, HMEC122L_SSC, HMEC240L_SSC
56 level 1 datasets: 8 for each cell line staining set combination excluding the SSC staining set
56 level 2 datasets: 8 for each cell line staining set combination excluding the SSC staining set
10 level 3 datasets: 1 for each study
10 level 4 datasets: 1 for each study
7 cell level QA reports: 1 for each cell line+staining set excluding the SSC staining set
7 spot and MEP QA reports: 1 for each cell line+staining set excluding the SSC staining set
10 analysis reports: 1 for each study

**Comment by kdaily** [comment]
@ychae I think we were good here, right? I know you told me, but please confirm (or add any notes of issues found or outstanding things to change). Thanks!

**Comment by ychae** [comment]
@kdaily Yep, it's all good to go! Was there a consensus on what to do about the NAs?

**Comment by kdaily** [comment]
Right! ~~Remove all NA values~~ Set all NA values to null (remove those annotations from entities) @ychae, please!

**Comment by ychae** [comment]
All done!
